// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SmartInverterAPI.Data;

#nullable disable

namespace SmartInverterAPI.Migrations
{
    [DbContext(typeof(InverterContext))]
    [Migration("20220707111816_RemoveTimeIntervalColumnScript")]
    partial class RemoveTimeIntervalColumnScript
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("SmartInverterAPI.Models.LastDayData", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<decimal>("AvgLoadWatts")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("AvgSolarOutputWatts")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("BatteryPerc")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("ConsumptionWh")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("Day")
                        .HasColumnType("int");

                    b.Property<int>("Hour")
                        .HasColumnType("int");

                    b.Property<DateTime>("LoggedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("PowerSource")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("SampleCount")
                        .HasColumnType("int");

                    b.Property<decimal>("SolarGeneratedWh")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.ToTable("LastDayData");
                });

            modelBuilder.Entity("SmartInverterAPI.Models.LastDecadeData", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<decimal>("AvgLoadWatts")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("AvgSolarOutputWatts")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("BatteryPerc")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("ConsumptionWh")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("LoggedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("PowerSource")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("SampleCount")
                        .HasColumnType("int");

                    b.Property<decimal>("SolarGeneratedWh")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("Year")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("LastDecadeData");
                });

            modelBuilder.Entity("SmartInverterAPI.Models.LastHourData", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<decimal>("AvgLoadWatts")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("AvgSolarOutputWatts")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("BatteryPerc")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("ConsumptionWh")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("Hour")
                        .HasColumnType("int");

                    b.Property<DateTime>("LoggedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("Minute")
                        .HasColumnType("int");

                    b.Property<string>("PowerSource")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("SampleCount")
                        .HasColumnType("int");

                    b.Property<decimal>("SolarGeneratedWh")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.ToTable("LastHourData");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AvgLoadWatts = 0m,
                            AvgSolarOutputWatts = 0m,
                            BatteryPerc = 0m,
                            ConsumptionWh = 0m,
                            Hour = 0,
                            LoggedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Minute = 0,
                            SampleCount = 0,
                            SolarGeneratedWh = 0m
                        },
                        new
                        {
                            Id = 2,
                            AvgLoadWatts = 0m,
                            AvgSolarOutputWatts = 0m,
                            BatteryPerc = 0m,
                            ConsumptionWh = 0m,
                            Hour = 0,
                            LoggedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Minute = 1,
                            SampleCount = 0,
                            SolarGeneratedWh = 0m
                        },
                        new
                        {
                            Id = 3,
                            AvgLoadWatts = 0m,
                            AvgSolarOutputWatts = 0m,
                            BatteryPerc = 0m,
                            ConsumptionWh = 0m,
                            Hour = 0,
                            LoggedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Minute = 2,
                            SampleCount = 0,
                            SolarGeneratedWh = 0m
                        },
                        new
                        {
                            Id = 4,
                            AvgLoadWatts = 0m,
                            AvgSolarOutputWatts = 0m,
                            BatteryPerc = 0m,
                            ConsumptionWh = 0m,
                            Hour = 0,
                            LoggedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Minute = 3,
                            SampleCount = 0,
                            SolarGeneratedWh = 0m
                        },
                        new
                        {
                            Id = 5,
                            AvgLoadWatts = 0m,
                            AvgSolarOutputWatts = 0m,
                            BatteryPerc = 0m,
                            ConsumptionWh = 0m,
                            Hour = 0,
                            LoggedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Minute = 4,
                            SampleCount = 0,
                            SolarGeneratedWh = 0m
                        },
                        new
                        {
                            Id = 6,
                            AvgLoadWatts = 0m,
                            AvgSolarOutputWatts = 0m,
                            BatteryPerc = 0m,
                            ConsumptionWh = 0m,
                            Hour = 0,
                            LoggedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Minute = 5,
                            SampleCount = 0,
                            SolarGeneratedWh = 0m
                        },
                        new
                        {
                            Id = 7,
                            AvgLoadWatts = 0m,
                            AvgSolarOutputWatts = 0m,
                            BatteryPerc = 0m,
                            ConsumptionWh = 0m,
                            Hour = 0,
                            LoggedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Minute = 6,
                            SampleCount = 0,
                            SolarGeneratedWh = 0m
                        },
                        new
                        {
                            Id = 8,
                            AvgLoadWatts = 0m,
                            AvgSolarOutputWatts = 0m,
                            BatteryPerc = 0m,
                            ConsumptionWh = 0m,
                            Hour = 0,
                            LoggedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Minute = 7,
                            SampleCount = 0,
                            SolarGeneratedWh = 0m
                        },
                        new
                        {
                            Id = 9,
                            AvgLoadWatts = 0m,
                            AvgSolarOutputWatts = 0m,
                            BatteryPerc = 0m,
                            ConsumptionWh = 0m,
                            Hour = 0,
                            LoggedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Minute = 8,
                            SampleCount = 0,
                            SolarGeneratedWh = 0m
                        },
                        new
                        {
                            Id = 10,
                            AvgLoadWatts = 0m,
                            AvgSolarOutputWatts = 0m,
                            BatteryPerc = 0m,
                            ConsumptionWh = 0m,
                            Hour = 0,
                            LoggedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Minute = 9,
                            SampleCount = 0,
                            SolarGeneratedWh = 0m
                        },
                        new
                        {
                            Id = 11,
                            AvgLoadWatts = 0m,
                            AvgSolarOutputWatts = 0m,
                            BatteryPerc = 0m,
                            ConsumptionWh = 0m,
                            Hour = 0,
                            LoggedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Minute = 10,
                            SampleCount = 0,
                            SolarGeneratedWh = 0m
                        },
                        new
                        {
                            Id = 12,
                            AvgLoadWatts = 0m,
                            AvgSolarOutputWatts = 0m,
                            BatteryPerc = 0m,
                            ConsumptionWh = 0m,
                            Hour = 0,
                            LoggedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Minute = 11,
                            SampleCount = 0,
                            SolarGeneratedWh = 0m
                        },
                        new
                        {
                            Id = 13,
                            AvgLoadWatts = 0m,
                            AvgSolarOutputWatts = 0m,
                            BatteryPerc = 0m,
                            ConsumptionWh = 0m,
                            Hour = 0,
                            LoggedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Minute = 12,
                            SampleCount = 0,
                            SolarGeneratedWh = 0m
                        },
                        new
                        {
                            Id = 14,
                            AvgLoadWatts = 0m,
                            AvgSolarOutputWatts = 0m,
                            BatteryPerc = 0m,
                            ConsumptionWh = 0m,
                            Hour = 0,
                            LoggedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Minute = 13,
                            SampleCount = 0,
                            SolarGeneratedWh = 0m
                        },
                        new
                        {
                            Id = 15,
                            AvgLoadWatts = 0m,
                            AvgSolarOutputWatts = 0m,
                            BatteryPerc = 0m,
                            ConsumptionWh = 0m,
                            Hour = 0,
                            LoggedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Minute = 14,
                            SampleCount = 0,
                            SolarGeneratedWh = 0m
                        },
                        new
                        {
                            Id = 16,
                            AvgLoadWatts = 0m,
                            AvgSolarOutputWatts = 0m,
                            BatteryPerc = 0m,
                            ConsumptionWh = 0m,
                            Hour = 0,
                            LoggedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Minute = 15,
                            SampleCount = 0,
                            SolarGeneratedWh = 0m
                        },
                        new
                        {
                            Id = 17,
                            AvgLoadWatts = 0m,
                            AvgSolarOutputWatts = 0m,
                            BatteryPerc = 0m,
                            ConsumptionWh = 0m,
                            Hour = 0,
                            LoggedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Minute = 16,
                            SampleCount = 0,
                            SolarGeneratedWh = 0m
                        },
                        new
                        {
                            Id = 18,
                            AvgLoadWatts = 0m,
                            AvgSolarOutputWatts = 0m,
                            BatteryPerc = 0m,
                            ConsumptionWh = 0m,
                            Hour = 0,
                            LoggedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Minute = 17,
                            SampleCount = 0,
                            SolarGeneratedWh = 0m
                        },
                        new
                        {
                            Id = 19,
                            AvgLoadWatts = 0m,
                            AvgSolarOutputWatts = 0m,
                            BatteryPerc = 0m,
                            ConsumptionWh = 0m,
                            Hour = 0,
                            LoggedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Minute = 18,
                            SampleCount = 0,
                            SolarGeneratedWh = 0m
                        },
                        new
                        {
                            Id = 20,
                            AvgLoadWatts = 0m,
                            AvgSolarOutputWatts = 0m,
                            BatteryPerc = 0m,
                            ConsumptionWh = 0m,
                            Hour = 0,
                            LoggedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Minute = 19,
                            SampleCount = 0,
                            SolarGeneratedWh = 0m
                        },
                        new
                        {
                            Id = 21,
                            AvgLoadWatts = 0m,
                            AvgSolarOutputWatts = 0m,
                            BatteryPerc = 0m,
                            ConsumptionWh = 0m,
                            Hour = 0,
                            LoggedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Minute = 20,
                            SampleCount = 0,
                            SolarGeneratedWh = 0m
                        },
                        new
                        {
                            Id = 22,
                            AvgLoadWatts = 0m,
                            AvgSolarOutputWatts = 0m,
                            BatteryPerc = 0m,
                            ConsumptionWh = 0m,
                            Hour = 0,
                            LoggedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Minute = 21,
                            SampleCount = 0,
                            SolarGeneratedWh = 0m
                        },
                        new
                        {
                            Id = 23,
                            AvgLoadWatts = 0m,
                            AvgSolarOutputWatts = 0m,
                            BatteryPerc = 0m,
                            ConsumptionWh = 0m,
                            Hour = 0,
                            LoggedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Minute = 22,
                            SampleCount = 0,
                            SolarGeneratedWh = 0m
                        },
                        new
                        {
                            Id = 24,
                            AvgLoadWatts = 0m,
                            AvgSolarOutputWatts = 0m,
                            BatteryPerc = 0m,
                            ConsumptionWh = 0m,
                            Hour = 0,
                            LoggedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Minute = 23,
                            SampleCount = 0,
                            SolarGeneratedWh = 0m
                        },
                        new
                        {
                            Id = 25,
                            AvgLoadWatts = 0m,
                            AvgSolarOutputWatts = 0m,
                            BatteryPerc = 0m,
                            ConsumptionWh = 0m,
                            Hour = 0,
                            LoggedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Minute = 24,
                            SampleCount = 0,
                            SolarGeneratedWh = 0m
                        },
                        new
                        {
                            Id = 26,
                            AvgLoadWatts = 0m,
                            AvgSolarOutputWatts = 0m,
                            BatteryPerc = 0m,
                            ConsumptionWh = 0m,
                            Hour = 0,
                            LoggedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Minute = 25,
                            SampleCount = 0,
                            SolarGeneratedWh = 0m
                        },
                        new
                        {
                            Id = 27,
                            AvgLoadWatts = 0m,
                            AvgSolarOutputWatts = 0m,
                            BatteryPerc = 0m,
                            ConsumptionWh = 0m,
                            Hour = 0,
                            LoggedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Minute = 26,
                            SampleCount = 0,
                            SolarGeneratedWh = 0m
                        },
                        new
                        {
                            Id = 28,
                            AvgLoadWatts = 0m,
                            AvgSolarOutputWatts = 0m,
                            BatteryPerc = 0m,
                            ConsumptionWh = 0m,
                            Hour = 0,
                            LoggedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Minute = 27,
                            SampleCount = 0,
                            SolarGeneratedWh = 0m
                        },
                        new
                        {
                            Id = 29,
                            AvgLoadWatts = 0m,
                            AvgSolarOutputWatts = 0m,
                            BatteryPerc = 0m,
                            ConsumptionWh = 0m,
                            Hour = 0,
                            LoggedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Minute = 28,
                            SampleCount = 0,
                            SolarGeneratedWh = 0m
                        },
                        new
                        {
                            Id = 30,
                            AvgLoadWatts = 0m,
                            AvgSolarOutputWatts = 0m,
                            BatteryPerc = 0m,
                            ConsumptionWh = 0m,
                            Hour = 0,
                            LoggedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Minute = 29,
                            SampleCount = 0,
                            SolarGeneratedWh = 0m
                        },
                        new
                        {
                            Id = 31,
                            AvgLoadWatts = 0m,
                            AvgSolarOutputWatts = 0m,
                            BatteryPerc = 0m,
                            ConsumptionWh = 0m,
                            Hour = 0,
                            LoggedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Minute = 30,
                            SampleCount = 0,
                            SolarGeneratedWh = 0m
                        },
                        new
                        {
                            Id = 32,
                            AvgLoadWatts = 0m,
                            AvgSolarOutputWatts = 0m,
                            BatteryPerc = 0m,
                            ConsumptionWh = 0m,
                            Hour = 0,
                            LoggedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Minute = 31,
                            SampleCount = 0,
                            SolarGeneratedWh = 0m
                        },
                        new
                        {
                            Id = 33,
                            AvgLoadWatts = 0m,
                            AvgSolarOutputWatts = 0m,
                            BatteryPerc = 0m,
                            ConsumptionWh = 0m,
                            Hour = 0,
                            LoggedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Minute = 32,
                            SampleCount = 0,
                            SolarGeneratedWh = 0m
                        },
                        new
                        {
                            Id = 34,
                            AvgLoadWatts = 0m,
                            AvgSolarOutputWatts = 0m,
                            BatteryPerc = 0m,
                            ConsumptionWh = 0m,
                            Hour = 0,
                            LoggedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Minute = 33,
                            SampleCount = 0,
                            SolarGeneratedWh = 0m
                        },
                        new
                        {
                            Id = 35,
                            AvgLoadWatts = 0m,
                            AvgSolarOutputWatts = 0m,
                            BatteryPerc = 0m,
                            ConsumptionWh = 0m,
                            Hour = 0,
                            LoggedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Minute = 34,
                            SampleCount = 0,
                            SolarGeneratedWh = 0m
                        },
                        new
                        {
                            Id = 36,
                            AvgLoadWatts = 0m,
                            AvgSolarOutputWatts = 0m,
                            BatteryPerc = 0m,
                            ConsumptionWh = 0m,
                            Hour = 0,
                            LoggedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Minute = 35,
                            SampleCount = 0,
                            SolarGeneratedWh = 0m
                        },
                        new
                        {
                            Id = 37,
                            AvgLoadWatts = 0m,
                            AvgSolarOutputWatts = 0m,
                            BatteryPerc = 0m,
                            ConsumptionWh = 0m,
                            Hour = 0,
                            LoggedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Minute = 36,
                            SampleCount = 0,
                            SolarGeneratedWh = 0m
                        },
                        new
                        {
                            Id = 38,
                            AvgLoadWatts = 0m,
                            AvgSolarOutputWatts = 0m,
                            BatteryPerc = 0m,
                            ConsumptionWh = 0m,
                            Hour = 0,
                            LoggedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Minute = 37,
                            SampleCount = 0,
                            SolarGeneratedWh = 0m
                        },
                        new
                        {
                            Id = 39,
                            AvgLoadWatts = 0m,
                            AvgSolarOutputWatts = 0m,
                            BatteryPerc = 0m,
                            ConsumptionWh = 0m,
                            Hour = 0,
                            LoggedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Minute = 38,
                            SampleCount = 0,
                            SolarGeneratedWh = 0m
                        },
                        new
                        {
                            Id = 40,
                            AvgLoadWatts = 0m,
                            AvgSolarOutputWatts = 0m,
                            BatteryPerc = 0m,
                            ConsumptionWh = 0m,
                            Hour = 0,
                            LoggedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Minute = 39,
                            SampleCount = 0,
                            SolarGeneratedWh = 0m
                        },
                        new
                        {
                            Id = 41,
                            AvgLoadWatts = 0m,
                            AvgSolarOutputWatts = 0m,
                            BatteryPerc = 0m,
                            ConsumptionWh = 0m,
                            Hour = 0,
                            LoggedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Minute = 40,
                            SampleCount = 0,
                            SolarGeneratedWh = 0m
                        },
                        new
                        {
                            Id = 42,
                            AvgLoadWatts = 0m,
                            AvgSolarOutputWatts = 0m,
                            BatteryPerc = 0m,
                            ConsumptionWh = 0m,
                            Hour = 0,
                            LoggedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Minute = 41,
                            SampleCount = 0,
                            SolarGeneratedWh = 0m
                        },
                        new
                        {
                            Id = 43,
                            AvgLoadWatts = 0m,
                            AvgSolarOutputWatts = 0m,
                            BatteryPerc = 0m,
                            ConsumptionWh = 0m,
                            Hour = 0,
                            LoggedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Minute = 42,
                            SampleCount = 0,
                            SolarGeneratedWh = 0m
                        },
                        new
                        {
                            Id = 44,
                            AvgLoadWatts = 0m,
                            AvgSolarOutputWatts = 0m,
                            BatteryPerc = 0m,
                            ConsumptionWh = 0m,
                            Hour = 0,
                            LoggedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Minute = 43,
                            SampleCount = 0,
                            SolarGeneratedWh = 0m
                        },
                        new
                        {
                            Id = 45,
                            AvgLoadWatts = 0m,
                            AvgSolarOutputWatts = 0m,
                            BatteryPerc = 0m,
                            ConsumptionWh = 0m,
                            Hour = 0,
                            LoggedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Minute = 44,
                            SampleCount = 0,
                            SolarGeneratedWh = 0m
                        },
                        new
                        {
                            Id = 46,
                            AvgLoadWatts = 0m,
                            AvgSolarOutputWatts = 0m,
                            BatteryPerc = 0m,
                            ConsumptionWh = 0m,
                            Hour = 0,
                            LoggedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Minute = 45,
                            SampleCount = 0,
                            SolarGeneratedWh = 0m
                        },
                        new
                        {
                            Id = 47,
                            AvgLoadWatts = 0m,
                            AvgSolarOutputWatts = 0m,
                            BatteryPerc = 0m,
                            ConsumptionWh = 0m,
                            Hour = 0,
                            LoggedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Minute = 46,
                            SampleCount = 0,
                            SolarGeneratedWh = 0m
                        },
                        new
                        {
                            Id = 48,
                            AvgLoadWatts = 0m,
                            AvgSolarOutputWatts = 0m,
                            BatteryPerc = 0m,
                            ConsumptionWh = 0m,
                            Hour = 0,
                            LoggedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Minute = 47,
                            SampleCount = 0,
                            SolarGeneratedWh = 0m
                        },
                        new
                        {
                            Id = 49,
                            AvgLoadWatts = 0m,
                            AvgSolarOutputWatts = 0m,
                            BatteryPerc = 0m,
                            ConsumptionWh = 0m,
                            Hour = 0,
                            LoggedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Minute = 48,
                            SampleCount = 0,
                            SolarGeneratedWh = 0m
                        },
                        new
                        {
                            Id = 50,
                            AvgLoadWatts = 0m,
                            AvgSolarOutputWatts = 0m,
                            BatteryPerc = 0m,
                            ConsumptionWh = 0m,
                            Hour = 0,
                            LoggedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Minute = 49,
                            SampleCount = 0,
                            SolarGeneratedWh = 0m
                        },
                        new
                        {
                            Id = 51,
                            AvgLoadWatts = 0m,
                            AvgSolarOutputWatts = 0m,
                            BatteryPerc = 0m,
                            ConsumptionWh = 0m,
                            Hour = 0,
                            LoggedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Minute = 50,
                            SampleCount = 0,
                            SolarGeneratedWh = 0m
                        },
                        new
                        {
                            Id = 52,
                            AvgLoadWatts = 0m,
                            AvgSolarOutputWatts = 0m,
                            BatteryPerc = 0m,
                            ConsumptionWh = 0m,
                            Hour = 0,
                            LoggedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Minute = 51,
                            SampleCount = 0,
                            SolarGeneratedWh = 0m
                        },
                        new
                        {
                            Id = 53,
                            AvgLoadWatts = 0m,
                            AvgSolarOutputWatts = 0m,
                            BatteryPerc = 0m,
                            ConsumptionWh = 0m,
                            Hour = 0,
                            LoggedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Minute = 52,
                            SampleCount = 0,
                            SolarGeneratedWh = 0m
                        },
                        new
                        {
                            Id = 54,
                            AvgLoadWatts = 0m,
                            AvgSolarOutputWatts = 0m,
                            BatteryPerc = 0m,
                            ConsumptionWh = 0m,
                            Hour = 0,
                            LoggedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Minute = 53,
                            SampleCount = 0,
                            SolarGeneratedWh = 0m
                        },
                        new
                        {
                            Id = 55,
                            AvgLoadWatts = 0m,
                            AvgSolarOutputWatts = 0m,
                            BatteryPerc = 0m,
                            ConsumptionWh = 0m,
                            Hour = 0,
                            LoggedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Minute = 54,
                            SampleCount = 0,
                            SolarGeneratedWh = 0m
                        },
                        new
                        {
                            Id = 56,
                            AvgLoadWatts = 0m,
                            AvgSolarOutputWatts = 0m,
                            BatteryPerc = 0m,
                            ConsumptionWh = 0m,
                            Hour = 0,
                            LoggedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Minute = 55,
                            SampleCount = 0,
                            SolarGeneratedWh = 0m
                        },
                        new
                        {
                            Id = 57,
                            AvgLoadWatts = 0m,
                            AvgSolarOutputWatts = 0m,
                            BatteryPerc = 0m,
                            ConsumptionWh = 0m,
                            Hour = 0,
                            LoggedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Minute = 56,
                            SampleCount = 0,
                            SolarGeneratedWh = 0m
                        },
                        new
                        {
                            Id = 58,
                            AvgLoadWatts = 0m,
                            AvgSolarOutputWatts = 0m,
                            BatteryPerc = 0m,
                            ConsumptionWh = 0m,
                            Hour = 0,
                            LoggedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Minute = 57,
                            SampleCount = 0,
                            SolarGeneratedWh = 0m
                        },
                        new
                        {
                            Id = 59,
                            AvgLoadWatts = 0m,
                            AvgSolarOutputWatts = 0m,
                            BatteryPerc = 0m,
                            ConsumptionWh = 0m,
                            Hour = 0,
                            LoggedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Minute = 58,
                            SampleCount = 0,
                            SolarGeneratedWh = 0m
                        },
                        new
                        {
                            Id = 60,
                            AvgLoadWatts = 0m,
                            AvgSolarOutputWatts = 0m,
                            BatteryPerc = 0m,
                            ConsumptionWh = 0m,
                            Hour = 0,
                            LoggedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Minute = 59,
                            SampleCount = 0,
                            SolarGeneratedWh = 0m
                        });
                });

            modelBuilder.Entity("SmartInverterAPI.Models.LastYearData", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<decimal>("AvgLoadWatts")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("AvgSolarOutputWatts")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("BatteryPerc")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("ConsumptionWh")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("LoggedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("Month")
                        .HasColumnType("int");

                    b.Property<string>("PowerSource")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("SampleCount")
                        .HasColumnType("int");

                    b.Property<decimal>("SolarGeneratedWh")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("Year")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("LastYearData");
                });

            modelBuilder.Entity("SmartInverterAPI.Models.RawData", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"), 1L, 1);

                    b.Property<decimal>("BatteryPerc")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("ConsumptionWh")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("LoadWatts")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("LoggedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("PowerSource")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("SolarGeneratedWh")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("SolarOutputWatts")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("TimeIntervalSec")
                        .HasColumnType("int");

                    b.HasKey("id");

                    b.ToTable("RawData");
                });
#pragma warning restore 612, 618
        }
    }
}
